// <auto-generated />
using HCM_app.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCM_app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510072815_NewData")]
    partial class NewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedModels.UserDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UserDataModel");

                    b.HasData(
                        new
                        {
                            Id = "c371a2bd-2054-4d70-ae74-220ab964db23",
                            Department = "Human Resources",
                            Email = "john.doe@company.com",
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Password = "john123",
                            PasswordHash = "$2a$11$CAsvsc6Wb/zLl9kVw56PXuDHkqnuYL0DuGXg6bOfxq4bCVTSHwdZy",
                            Role = 2,
                            Salary = 60000.0
                        },
                        new
                        {
                            Id = "67766b45-df0b-47df-aa34-ccd42f41a622",
                            Department = "IT",
                            Email = "alice.smith@company.com",
                            FirstName = "Alice",
                            JobTitle = "Software Developer",
                            LastName = "Smith",
                            Password = "alice123",
                            PasswordHash = "$2a$11$5IkuPwvTCoV1E0f07isFT.sc5ODdMHBEkZ3LAdkp9p8Ht9Ia5TbhO",
                            Role = 0,
                            Salary = 55000.0
                        },
                        new
                        {
                            Id = "3b15153b-9d74-48bd-951f-a9ccdb60be55",
                            Department = "IT",
                            Email = "bob.brown@company.com",
                            FirstName = "Bob",
                            JobTitle = "IT Manager",
                            LastName = "Brown",
                            Password = "bob123",
                            PasswordHash = "$2a$11$0oeRcWuGYln89tEN0ZGRL.yTTSXHpsE893hkQdBC0alOcct8CIGlS",
                            Role = 1,
                            Salary = 70000.0
                        },
                        new
                        {
                            Id = "95ba2835-f31f-4f1b-92a5-c2c994834555",
                            Department = "Analytics",
                            Email = "eve.white@company.com",
                            FirstName = "Eve",
                            JobTitle = "Data Analyst",
                            LastName = "White",
                            Password = "eve123",
                            PasswordHash = "$2a$11$VvcM/raekBkc706DIzVKEOeiWwf3P7UzVtpyPjmoFd3PGZGNfNyga",
                            Role = 0,
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = "aff067fa-1533-4bf0-9d66-9c2a5ec68e03",
                            Department = "Finance",
                            Email = "charlie.black@company.com",
                            FirstName = "Charlie",
                            JobTitle = "Finance Manager",
                            LastName = "Black",
                            Password = "charlie123",
                            PasswordHash = "$2a$11$8JL/YIJPTM2Y5zu8dBQtY.0BaBm5fCVlXCVWf3atMHfHU2BACPy.i",
                            Role = 1,
                            Salary = 65000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
