// <auto-generated />
using HCM_app.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCM_app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250515163129_NewSeeding")]
    partial class NewSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedModels.UserDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "f9bb6005-13be-441f-ac07-51d1c30bf753",
                            Department = "HR",
                            Email = "nelvin@email.com",
                            FirstName = "Nelvin",
                            JobTitle = "Human Resources",
                            LastName = "Lorance",
                            PasswordHash = "$2a$11$WZocNhN.MJxzlj3mz/BwPOFbHLEUQiIz4bEPj.OsdwJBVfVFtiTVy",
                            Role = "Employee",
                            Salary = 70000.0
                        },
                        new
                        {
                            Id = "5e799534-9d9b-4946-83e3-e10728756b44",
                            Department = "Human Resources",
                            Email = "admin@email.com",
                            FirstName = "George",
                            JobTitle = "HR Admin",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$WZocNhN.MJxzlj3mz/BwPOFbHLEUQiIz4bEPj.OsdwJBVfVFtiTVy",
                            Role = "HrAdmin",
                            Salary = 999999.0
                        },
                        new
                        {
                            Id = "5fdb35d2-c603-4b07-a783-5ec05236f24e",
                            Department = "Human Resources",
                            Email = "chris@email.com",
                            FirstName = "Chris",
                            JobTitle = "HR",
                            LastName = "Hemsworth",
                            PasswordHash = "$2a$11$H3xdw69rCOAfbcvCFoQbfOEUETlGefP/LlQH/AvfEgPu4vbeueEAC",
                            Role = "Employee",
                            Salary = 200000.0
                        },
                        new
                        {
                            Id = "969320d6-9770-4563-a40f-8274c70dfca8",
                            Department = "IT",
                            Email = "scott@email.com",
                            FirstName = "Scott",
                            JobTitle = "Software Engineer",
                            LastName = "Marry",
                            PasswordHash = "$2a$11$P3.TYLdNnt5xzZrW/2YuB.FhZMXs.fC5ELJqb1RD7aBG2rrF6piTy",
                            Role = "Employee",
                            Salary = 90000.0
                        },
                        new
                        {
                            Id = "a27155e7-6576-4533-82c2-aa57c9599bfd",
                            Department = "Human Resources",
                            Email = "lenny@email.com",
                            FirstName = "Lenny",
                            JobTitle = "HR",
                            LastName = "Arkan",
                            PasswordHash = "$2a$11$irHeELEwpnvOuM61ZECN..lP.jVDvasyWnT3zEJi.7zHyQU1DDsvS",
                            Role = "Employee",
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = "f2a46a35-e51f-499f-b169-ea21aa78bb20",
                            Department = "Human Resources",
                            Email = "manager@email.com",
                            FirstName = "Manny",
                            JobTitle = "HR Manager",
                            LastName = "Wonder",
                            PasswordHash = "$2a$11$ewWndEf7eJjhzK22PfjZs.HvSiu2KWz492yicZxigElpSoT0tP7p2",
                            Role = "Manager",
                            Salary = 922222.0
                        },
                        new
                        {
                            Id = "31815e61-2406-4703-9b34-bf9f06f0cbab",
                            Department = "IT",
                            Email = "bob@email.com",
                            FirstName = "Bob",
                            JobTitle = "Analysis",
                            LastName = "Bobson",
                            PasswordHash = "$2a$11$eVJ4rdurEyezkeBMLmqFIOPy5WsWqEagza5p.1izG9vTIgBJVJ7Ze",
                            Role = "Employee",
                            Salary = 23000.0
                        },
                        new
                        {
                            Id = "2001497d-2995-4a1a-a3c7-c979d8393764",
                            Department = "IT",
                            Email = "terry@email.com",
                            FirstName = "Terry",
                            JobTitle = "Software Engineer",
                            LastName = "Davis",
                            PasswordHash = "$2a$11$IE2aVv2PcArNUwv2y1BlkehB4STorUQn5NxsXeRLm2qXSCMwKTdDG",
                            Role = "Employee",
                            Salary = 239000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
