// <auto-generated />
using HCM_app.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCM_app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SharedModels.UserDataModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Department = "Human Resources",
                            Email = "john.doe@company.com",
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Password = "john123",
                            PasswordHash = "$2a$11$TGF/8C6lvCd2NwvIzyy7MO5zEVU0HbFi6Lcszz3vJ5Jb7IYgU4WQ6",
                            Role = 2,
                            Salary = 60000.0
                        },
                        new
                        {
                            Id = "2",
                            Department = "IT",
                            Email = "alice.smith@company.com",
                            FirstName = "Alice",
                            JobTitle = "Software Developer",
                            LastName = "Smith",
                            Password = "alice123",
                            PasswordHash = "$2a$11$6gHDwIT5oF7kPv/WsZ5xSuJZgYiy0qqosBHT5hyvTjxESfCLOEBoK",
                            Role = 0,
                            Salary = 55000.0
                        },
                        new
                        {
                            Id = "3",
                            Department = "IT",
                            Email = "bob.brown@company.com",
                            FirstName = "Bob",
                            JobTitle = "IT Manager",
                            LastName = "Brown",
                            Password = "bob123",
                            PasswordHash = "$2a$11$WkN0zZ6xNmBxLKNZKb7Lz.CDuvOl/aI6uR5Y31ECR6sIzLrz0xuU2",
                            Role = 1,
                            Salary = 70000.0
                        },
                        new
                        {
                            Id = "4",
                            Department = "Analytics",
                            Email = "eve.white@company.com",
                            FirstName = "Eve",
                            JobTitle = "Data Analyst",
                            LastName = "White",
                            Password = "eve123",
                            PasswordHash = "$2a$11$uFxI9zGB3EPPylxJzDJ01O9mxvhvn4tNzXn2uFub02YjKl3K5q6a6",
                            Role = 0,
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = "5",
                            Department = "Finance",
                            Email = "charlie.black@company.com",
                            FirstName = "Charlie",
                            JobTitle = "Finance Manager",
                            LastName = "Black",
                            Password = "charlie123",
                            PasswordHash = "$2a$11$ZOfVLQjZas3zF7TFoTeZp.7V/qew5cqvPcNCQs5tQZ0Txlri3F5FS",
                            Role = 1,
                            Salary = 65000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
